table monolingual if lanp == 625
table monolingual if lanp == 708
table monolingual if lanp == 742
table monolingual if lanp == 728
table monolingual if lanp == 724
table monolingual if lanp == 777
table monolingual if lanp == 639
table monolingual if lanp == 663
table monolingual if lanp == 629
table monolingual if lanp == 623
table monolingual if lanp == 712
table monolingual if lanp == 620
table monolingual if lanp == 711
table monolingual if lanp == 645
table monolingual if lanp == 671
table monolingual if lanp != 625

table bilingual if lanp == 625
table bilingual if lanp == 708
table bilingual if lanp == 742
table bilingual if lanp == 728
table bilingual if lanp == 724
table bilingual if lanp == 777
table bilingual if lanp == 639
table bilingual if lanp == 663
table bilingual if lanp == 629
table bilingual if lanp == 623
table bilingual if lanp == 712
table bilingual if lanp == 620
table bilingual if lanp == 711
table bilingual if lanp == 645
table bilingual if lanp == 671
table bilingual if lanp != 625
